// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1589193811);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1345);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1589193782);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a7a56d9c-7fdb-4f23-ad9b-2d62600babf6}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1589193786990");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1589197386990");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1589193785");
user_pref("browser.slowStartup.averageTime", 11800);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200429185419");
user_pref("browser.startup.homepage_override.mstone", "76.0");
user_pref("browser.startup.lastColdStartupCheck", 1589193783);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1589193785353");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "76.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "3fa16a7c4a2c46e09e46cfae26612b43");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "76.0");
user_pref("extensions.lastPlatformVersion", "76.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3e611ed0-52f8-4c9b-8ad0-10a446a6dbbb\",\"formautofill@mozilla.org\":\"b13065d4-e248-49a8-b0a0-373be65c0871\",\"screenshots@mozilla.org\":\"b35c7d7d-95dc-41ce-809e-eef5a6fad4dc\",\"webcompat-reporter@mozilla.org\":\"23c43bb4-7d3d-4aba-8908-81e53c9c6f68\",\"webcompat@mozilla.org\":\"ab26c9bb-35a1-4f2e-aaf1-7323aafa71e5\",\"default-theme@mozilla.org\":\"50c38d77-6703-48ab-ab88-d3ce8ca233c9\",\"google@search.mozilla.org\":\"4ed4c4b3-50c6-4718-afff-aa377c6d1095\",\"amazondotcom@search.mozilla.org\":\"e0c1a5d8-a529-4e81-b0cb-08c5e8179d0b\",\"bing@search.mozilla.org\":\"dd50ea2e-1cad-43ba-9547-c180dc585436\",\"ddg@search.mozilla.org\":\"5bc2ebee-1117-44a2-bce5-668aae13cf3c\",\"ebay@search.mozilla.org\":\"9b4f101b-6289-40df-a963-84676e943109\",\"twitter@search.mozilla.org\":\"c0a6f6be-6e8a-447b-958a-a90c4b7f2492\",\"wikipedia@search.mozilla.org\":\"ad563606-da1d-4323-bf23-5045bd97b275\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "397372e2-4d3f-42fe-9eb6-d72417f93f37");
user_pref("security.sandbox.plugin.tempDirSuffix", "000cc6f5-cb62-46ee-94e8-928ab82c1743");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1589193774);
user_pref("toolkit.telemetry.cachedClientID", "0aecad10-552e-421c-acf6-e43a92731600");
user_pref("toolkit.telemetry.previousBuildID", "20200429185419");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
